TRANSFORMED_DATA_SAVE_PATH="data/transformed-model-input-datasets"
INTRINSIC_DIM_DATASET="data/intrinsic-dim-dataset"
INFORMATICUP_TEXT_DATASET="data/informaticup-test-dataset/ai_gen_text"
INFORMATICUP_IMAGES_DATASET="data/informaticup-test-dataset/ai_gen_images"
PRE_TRAINED_MODELS="pre-trained-models"
ROBERTA_BASE="roberta-base"
HUMAN_TEXT_STR="human_text"
AI_GENERATED_TEXT_STR="ai_gen_text"
